title:              Garden Guys
email:              info@gardenguys.in
formspreeid:        mqkoonje
description:        Green tips for your garden paradise.
author:             Garden Guys
baseurl:            "/blog"
url:                "https://gardenguys.in"

# Social Profiles
twitter_username:   gardenguysin
github_username:    
facebook_username:  gardenguys.in
instagram_username:  gardenguys.in
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-6BPN9Q43PB # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
